[build]
target = "index.html"
dist = "dist"
pattern_script = '''
<script type="module">import init, { initThreadPool} from '{base}{js}'; await init('{base}{wasm}'); </script>
'''

# await init('{base}{wasm}'); await initThreadPool(navigator.hardwareConcurrency);

[serve.headers]
# see ./assets/_headers for more documentation
"cross-origin-embedder-policy"= "require-corp"
"cross-origin-opener-policy"= "same-origin"
"cross-origin-resource-policy"= "same-site"
